version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  commit-message:
    prefix: "fix(python dependencies): "
  schedule:
    interval: weekly
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: "/"
  commit-message:
    prefix: "fix(gha dependencies): "
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "actions/*"
- package-ecosystem: "npm"
  directory: "/excalidraw-renderer"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "fix(js dependencies): "
  groups:
    javascript-packages:
      patterns:
        - "*"