version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "actions/*"
- package-ecosystem: "npm"
  directory: "/excalidraw-renderer"
  schedule:
    interval: "weekly"
  groups:
    javascript-packages:
      patterns:
        - "*"