name: branches

on:
  push:
    branches:
      - fix/*
      - feat/*

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v6
      - name: 🤖 Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
      - name: 📦 Bundle JS
        run: make prod
      - name: 🧰 Install UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: 📥 Install dependencies
        run: uv sync --no-dev
      - name: 🧪 Run tests
        run: uv run pytest
      - name: 🏗️ Build package
        run: uv build
      