name: branches

on:
  push:
    branches:
      - fix/*
      - feat/*

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v7
      - name: 🤖 Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: 📦 Bundle JS
        run: make prod
      - name: 🐍 Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - name: 🧰 Install Poetry
        run: pip install poetry
      - name: 📥 Install dependencies
        run: poetry install --with dev --with docs
      - name: 🧪 Run tests
        run: poetry run pytest
      - name: 🏗️ Build package
        run: poetry build
      